/** Defaults do lote: base preta + letra branca (duas cores no 3MF). */
export const DEFAULT_KEYCHAIN_CONFIG = {
  line2: '',
  show2ndLine: false,
  faceDownMode: false,
  fontSize: 15,
  line2Offset: 0,
  line2VerticalOffset: -15,
  thickness: 2,
  textThickness: 1,
  keychainHoleSize: 4,
  keychainHoleOffset: 1,
  edgeRadius: 3,
  boxWidth: 0,
  boxHeight: 0,
  boxXOffset: 0,
  boxYOffset: -30,
  font: 'Chewy',
  fontStyle: 'Black',
  baseColor: '#000000',
  textColor: '#ffffff',
}
