/**
 * Lista bruta de supervisores/promotores (fonte da planilha).
 * Lindsay aparece duas vezes com diferença só de espaço antes do hífen —
 * a normalização em normalizeBatches funde esses lotes.
 */
export const RAW_SUPERVISOR_BATCHES = [
  {
    supervisor: 'ANA CRISTINA DOS SANTOS SIQUEIRA - 799987',
    promoters: [
      'ANIELE GUIMARAES',
      'ANTONIA ALVES',
      'BRYAN BRITO',
      'CLAUDIA CARDOSOS',
      'DIEGO DE MOURA',
      'GILBERTO TELES',
      'JOAO NASCIMENTO',
      'LIVRADA PINHEIRO',
      'LUCAS SIMON',
      'RENATO MIRANDA',
      'SABRINA PANTAROTO',
      'SELMA PIRES',
      'VIKTOR GOES',
      'ALESSANDRA SACCHI',
      'ARIADNE SANTOS',
    ],
  },
  {
    supervisor: 'KALEL ANDREI CAMARGO - 507054',
    promoters: [
      'ALEXSANDER BATISTA',
      'AMANDA FIGUEREDO',
      'AMANDA CAMPOS',
      'CRISTILIANE BRAZ',
      'DANILO FIGUEIREDO',
      'EDERSON BERTO',
      'EDUARDO PATROCINIO',
      'GISELLE PEREIRA',
      'ISABELA OLIVEIRA',
      'JOYCE FREITAS',
      'JUNIOR OLIVEIRA',
      'LUIS PEREIRA',
      'LUIS DE SOUZA',
      'LUIZ DOUGLAS',
      'MARIA GESSICA',
      'MARIA SCHPCHACKI',
      'MARIVANE ZANELLA',
      'MARTA MARIA',
      'PAMELA ALEIXO',
      'RAFAELA CAVALCANTE',
      'SILMARA ARRUDA',
      'TATIANE GONDA',
      'WILLIAM NUNES',
      'BEATRIZ LUNA',
    ],
  },
  {
    supervisor: 'LINDSAY ZEFERINO MAIA - 462905',
    promoters: [
      'ALBERT SOUZA',
      'ALINE PEREIRA',
      'ALLYSON MAZZETTO',
      'GABRIELA PONTES',
      'GLAUCIA RIBEIRO',
      'JACSON MENEZES',
      'JAQUELINE FIDELIS',
      'JESSICA CASONATTO',
      'JOELSON DA SILVA',
      'JONATHAS BARBOSA',
      'KATIUSCIA GARCIA',
      'LETICIA LIMA',
      'MARIA JAQUELINE',
      'MARIA JULIENE',
      'RAIANE BORGES',
      'RAISA BARBOSA',
      'RAQUEL VIEIRA',
      'RENATA SANTOS',
      'RICARDO JUNIOR',
      'SEBASTIAO FIGUEIREDO',
      'VICTOR SILVA',
      'VIVIANE CRISTINA',
      'VIVIANE PEREIRA',
      'WILSON ADRIAO',
    ],
  },
  {
    supervisor: 'LINDSAY ZEFERINO MAIA- 462905',
    promoters: [
      'RAFAELA JUNQUEIRA',
      'HELOISA ALVES FERREIRA',
      'YSMAEL SILVA',
    ],
  },
  {
    supervisor: 'MARIA EDUARDA LOPES DA SILVA - 810142',
    promoters: [
      'ALEXANDRO ANDRADE',
      'AMANDA SOUZA',
      'CEZAR TRINDADES',
      'CLEBER LIZARDO',
      'DAIANE SILONIO',
      'DAYANE ALVES',
      'DOUGLAS SANTOS',
      'EDUARDA ALMEIDA',
      'ERLAINE CAPUCHO',
      'EVANDRO JOSE',
      'GILSILEIA BORGES',
      'GUILHERME LIMA',
      'INGRID BANDEIRA',
      'IRACY AIRES',
      'JEAN CARLOS',
      'JESSICA WENDY',
      'JOAO PAULO',
      'KAIO GUERRA',
      'KAYKE TEIXEIRA',
      'KELLEN COSTA',
      'LARYSSA ELAINE',
      'LARISSA SANTOS',
      'LEANDRO DA SILVA',
      'LUCIANE ALINE',
      'MARCIA ANDRADE',
      'MATEUS CARLOS',
      'MATHEUS EMMANUEL',
      'RAFAEL PEREIRA',
      'RENAN PEREIRA',
      'RUBENS SILVA',
      'SINESIO FRANCISCO',
      'THIAGO PINHEIRO',
      'WEVERTON SILVA',
      'WILLIAN TURRAO',
      'WLADIMIR RODRIGUES',
      'BRUNA BUENO',
      'CLAUDETE ALVES',
      'LUIZ GUSTAVO',
      'GUILHERME TURRAO',
    ],
  },
  {
    supervisor: 'MAURICIO RODRIGUES',
    promoters: [
      'ALINE DE MELO',
      'ANA ALVES',
      'ANDERSON FREIRE',
      'ANDREA FURLANI',
      'CLICIELE VIEIRA',
      'DIEGO GOMES',
      'EDNALVA BEZERRA',
      'ELIANE ROCHA',
      'ELAINE DE FREITAS',
      'ISAAC FERREIRA',
      'JAIRO MOREIRA',
      'JAQUELINE LACERDA',
      'MARIA DA CONCEICAO',
      'NATALIA MARQUES',
      'PATRICIA OLIVEIRA',
      'ROGERIO PEREIRA',
      'SIMONE RICARDO',
      'DANIEL LIMA',
      'CRISLAINE FERNANDA PATERO',
    ],
  },
  {
    supervisor: 'PAULA RAMOS CUSTODIO DE LIMA - 714285',
    promoters: [
      'BRUNA CAMPOS',
      'BRUNO MENDES',
      'DEBORA DE OLIVEIRA',
      'DIOGO AUGUSTO',
      'ELCIO DOS SANTOS',
      'ELIEL MACHADO',
      'HUMBERTO ANDRADE',
      'JACI DA SILVA',
      'JOSE FRANCISCO',
      'LUAN HENRIQUE',
      'MARIO RODRIGUES',
      'MARIANA OLIVEIRA',
      'MICHELLE ALMEIDA',
      'MISSIANE PEIXOTO',
      'SABRINA TORRES',
      'SAMUEL DOS SANTOS',
      'TATIANE ALVES',
      'THALIA RAMOS',
      'VALDERI ALVES',
      'VANESSA DE SOUSA',
      'VANESSA DOS SANTOS',
      'WESLEY SANTOS',
      'DANIEL SANTOS',
    ],
  },
  {
    supervisor: 'PAULA RAMOS CUSTODIO DE LIMA - 714286',
    promoters: ['JOHN ALVES'],
  },
  {
    supervisor: 'RB WELDER OLIVEIRA',
    promoters: [
      'Iuri Santana',
      'Ana Lucio',
      'ANA FREIRE',
      'GEOVANE RAMOS',
      'LUANA ANDRADE',
      'MARIELE FERNANDES',
      'ADRYANNE MUNIZ',
      'ALAN HENRIQUE',
      'DAYANE COPOLA',
      'MAYANNE MUNIZ',
      'PAULO HENRIQUE',
      'ARLEN TEIXEIRA',
      'RAQUEL BENEDITO',
    ],
  },
  {
    supervisor: 'VALTER LUIZ CERRI - 374872',
    promoters: [
      'ALEXSANDER SANTANA',
      'ANA LAURA',
      'CRISTIANO BELLUCIO',
      'JENIFFER ZANIOLLO',
      'JESSIKA CURTOLO',
      'JOSE JUNIOR',
      'KARINA ERBETTA',
      'LUCAS CARVALHO',
      'PAULO SERGIO',
      'TATIARA DE SOUSA',
      'WERICARLA ALVES',
      'ZULEIDE MOREIRA',
    ],
  },
  {
    supervisor: 'WAGNER MARTINS DA SILVA JUNIOR - 689385',
    promoters: [
      'ADRIANA FAGUNDES',
      'ANA CLAUDIA',
      'CAROLINA FIDELIS',
      'DIEGO LEAL',
      'FABIANA RODRIGUES',
      'FLAVIA LIMA',
      'GIOVANE PEREIRA',
      'GUSTAVO VINICIUS',
      'JANETE RODRIGUES',
      'JESSICA NOSULA',
      'JOAO PEDRO',
      'JOAO VICTOR',
      'LUIZ ALBANO',
      'MARTA GOMES',
      'PATRICIA PIMENTA',
      'PEDRO HENRIQUE',
      'RAPHAEL ROCHA',
      'SELMA ALVES',
      'WILLIAN DE JESUS',
      'GABRIEL AQUINO',
      'GUSTAVO BORGES',
    ],
  },
]
