/**
 * Lista bruta de supervisores/promotores (fonte da planilha).
 * Ana Cristina, Kalel e Lindsay removidos — lotes já impressos.
 */

/**
 * Lista atual para chaveiros em lote (linha 1 = nome, linha 2 = sobrenome).
 */
export const SUPERVISOR_KEYCHAIN_NAMES = [
  { line1: 'EVANDRO', line2: 'HENRIQUE' },
  { line1: 'MALU', line2: 'VALÉRIO' },
  { line1: 'WELDER', line2: 'OLIVEIRA' },
  { line1: 'TAIS', line2: 'FARIAS' },
  { line1: 'ANA', line2: 'SIQUEIRA' },
  { line1: 'PAULA', line2: 'RAMOS' },
  { line1: 'KALEL', line2: 'CAMARGO' },
  { line1: 'LINDSAY', line2: 'MAIA' },
  { line1: 'DUDA', line2: 'LOPES' },
  { line1: 'MARISA', line2: 'ASSIS' },
  { line1: 'MAURICIO', line2: 'RODRIGUES' },
  { line1: 'WAGNER', line2: 'JUNIOR' },
  { line1: 'GEOVANE', line2: 'SILVA' },
  { line1: 'JESSICA', line2: 'STRADIOTTI' },
]

export const RAW_SUPERVISOR_BATCHES = [
  {
    supervisor: 'MARIA EDUARDA LOPES DA SILVA - 810142',
    promoters: [
      'ALEXANDRO ANDRADE',
      'AMANDA SOUZA',
      'CEZAR TRINDADES',
      'CLEBER LIZARDO',
      'DAIANE SILONIO',
      'DAYANE ALVES',
      'DOUGLAS SANTOS',
      'EDUARDA ALMEIDA',
      'ERLAINE CAPUCHO',
      'EVANDRO JOSE',
      'GILSILEIA BORGES',
      'GUILHERME LIMA',
      'INGRID BANDEIRA',
      'IRACY AIRES',
      'JEAN CARLOS',
      'JESSICA WENDY',
      'JOAO PAULO',
      'KAIO GUERRA',
      'KAYKE TEIXEIRA',
      'KELLEN COSTA',
      'LARYSSA ELAINE',
      'LARISSA SANTOS',
      'LEANDRO DA SILVA',
      'LUCIANE ALINE',
      'MARCIA ANDRADE',
      'MATEUS CARLOS',
      'MATHEUS EMMANUEL',
      'RAFAEL PEREIRA',
      'RENAN PEREIRA',
      'RUBENS SILVA',
      'SINESIO FRANCISCO',
      'THIAGO PINHEIRO',
      'WEVERTON SILVA',
      'WILLIAN TURRAO',
      'WLADIMIR RODRIGUES',
      'BRUNA BUENO',
      'CLAUDETE ALVES',
      'LUIZ GUSTAVO',
      'GUILHERME TURRAO',
    ],
  },
  {
    supervisor: 'MAURICIO RODRIGUES',
    promoters: [
      'ALINE DE MELO',
      'ANA ALVES',
      'ANDERSON FREIRE',
      'ANDREA FURLANI',
      'CLICIELE VIEIRA',
      'DIEGO GOMES',
      'EDNALVA BEZERRA',
      'ELIANE ROCHA',
      'ELAINE DE FREITAS',
      'ISAAC FERREIRA',
      'JAIRO MOREIRA',
      'JAQUELINE LACERDA',
      'MARIA DA CONCEICAO',
      'NATALIA MARQUES',
      'PATRICIA OLIVEIRA',
      'ROGERIO PEREIRA',
      'SIMONE RICARDO',
      'DANIEL LIMA',
      'CRISLAINE FERNANDA PATERO',
    ],
  },
  {
    supervisor: 'PAULA RAMOS CUSTODIO DE LIMA - 714285',
    promoters: [
      'BRUNA CAMPOS',
      'BRUNO MENDES',
      'DEBORA DE OLIVEIRA',
      'DIOGO AUGUSTO',
      'ELCIO DOS SANTOS',
      'ELIEL MACHADO',
      'HUMBERTO ANDRADE',
      'JACI DA SILVA',
      'JOSE FRANCISCO',
      'LUAN HENRIQUE',
      'MARIO RODRIGUES',
      'MARIANA OLIVEIRA',
      'MICHELLE ALMEIDA',
      'MISSIANE PEIXOTO',
      'SABRINA TORRES',
      'SAMUEL DOS SANTOS',
      'TATIANE ALVES',
      'THALIA RAMOS',
      'VALDERI ALVES',
      'VANESSA DE SOUSA',
      'VANESSA DOS SANTOS',
      'WESLEY SANTOS',
      'DANIEL SANTOS',
    ],
  },
  {
    supervisor: 'PAULA RAMOS CUSTODIO DE LIMA - 714286',
    promoters: ['JOHN ALVES'],
  },
  {
    supervisor: 'RB WELDER OLIVEIRA',
    promoters: [
      'Iuri Santana',
      'Ana Lucio',
      'ANA FREIRE',
      'GEOVANE RAMOS',
      'LUANA ANDRADE',
      'MARIELE FERNANDES',
      'ADRYANNE MUNIZ',
      'ALAN HENRIQUE',
      'DAYANE COPOLA',
      'MAYANNE MUNIZ',
      'PAULO HENRIQUE',
      'ARLEN TEIXEIRA',
      'RAQUEL BENEDITO',
    ],
  },
  {
    supervisor: 'VALTER LUIZ CERRI - 374872',
    promoters: [
      'ALEXSANDER SANTANA',
      'ANA LAURA',
      'CRISTIANO BELLUCIO',
      'JENIFFER ZANIOLLO',
      'JESSIKA CURTOLO',
      'JOSE JUNIOR',
      'KARINA ERBETTA',
      'LUCAS CARVALHO',
      'PAULO SERGIO',
      'TATIARA DE SOUSA',
      'WERICARLA ALVES',
      'ZULEIDE MOREIRA',
    ],
  },
  {
    supervisor: 'WAGNER MARTINS - 689385',
    promoters: [
      'ADRIANA FAGUNDES',
      'ANA CLAUDIA',
      'CAROLINA FIDELIS',
      'DIEGO LEAL',
      'FABIANA RODRIGUES',
      'FLAVIA LIMA',
      'GIOVANE PEREIRA',
      'GUSTAVO VINICIUS',
      'JANETE RODRIGUES',
      'JESSICA NOSULA',
      'JOAO PEDRO',
      'JOAO VICTOR',
      'LUIZ ALBANO',
      'MARTA GOMES',
      'PATRICIA PIMENTA',
      'PEDRO HENRIQUE',
      'RAPHAEL ROCHA',
      'SELMA ALVES',
      'WILLIAN DE JESUS',
      'GABRIEL AQUINO',
      'GUSTAVO BORGES',
    ],
  },
]
